// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9Tv-FgxAPR4L3bkHDAzrHOPWtrdwsPuc',
    appId: '1:157472745124:web:8a6bae51b4e221a26c2831',
    messagingSenderId: '157472745124',
    projectId: 'basededatos-myhomework',
    authDomain: 'basededatos-myhomework.firebaseapp.com',
    storageBucket: 'basededatos-myhomework.firebasestorage.app',
    measurementId: 'G-SMJCL9JPGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVw6tTV1BzMUZjNk6vwFPZ1MiY8zLLadA',
    appId: '1:157472745124:android:a6eb6f05524a81d66c2831',
    messagingSenderId: '157472745124',
    projectId: 'basededatos-myhomework',
    storageBucket: 'basededatos-myhomework.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Dba3ZfmCSAlDOsIt1qH04F1EQkRpzjI',
    appId: '1:157472745124:ios:cdbd3a8f11a63d8d6c2831',
    messagingSenderId: '157472745124',
    projectId: 'basededatos-myhomework',
    storageBucket: 'basededatos-myhomework.firebasestorage.app',
    iosBundleId: 'cl.davidmarvel2409.myhomework',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3Dba3ZfmCSAlDOsIt1qH04F1EQkRpzjI',
    appId: '1:157472745124:ios:2fc5405560ed005e6c2831',
    messagingSenderId: '157472745124',
    projectId: 'basededatos-myhomework',
    storageBucket: 'basededatos-myhomework.firebasestorage.app',
    iosBundleId: 'com.example.myhomework',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9Tv-FgxAPR4L3bkHDAzrHOPWtrdwsPuc',
    appId: '1:157472745124:web:b500fb7919de2b8a6c2831',
    messagingSenderId: '157472745124',
    projectId: 'basededatos-myhomework',
    authDomain: 'basededatos-myhomework.firebaseapp.com',
    storageBucket: 'basededatos-myhomework.firebasestorage.app',
    measurementId: 'G-4S37HSBK3H',
  );
}
